# Generated by Django 5.1.6 on 2025-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('sodium', models.FloatField()),
                ('sugar', models.FloatField()),
                ('fiber', models.FloatField()),
                ('iron', models.FloatField()),
                ('calcium', models.FloatField()),
                ('vitamin_a', models.FloatField()),
                ('vitamin_c', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('activity_level', models.CharField(max_length=50)),
                ('macro_requirements', models.JSONField()),
                ('micro_requirements', models.JSONField()),
            ],
        ),
    ]
