# Generated by Django 5.1.6 on 2025-02-10 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_nutritiondata_calcium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('daily_calories', models.FloatField()),
                ('carbs_percentage', models.CharField(default='50-60%', max_length=50)),
                ('protein_percentage', models.CharField(default='10-20%', max_length=50)),
                ('fat_percentage', models.CharField(default='20-30%', max_length=50)),
                ('calcium_mg', models.FloatField(default=1000)),
                ('iron_mg', models.FloatField(default=18)),
                ('vitamin_c_mg', models.FloatField(default=90)),
            ],
        ),
        migrations.DeleteModel(
            name='NutritionData',
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Little or no exercise (BMR × 1.2)'), ('Lightly Active', 'Light exercise 1-3 days/week (BMR × 1.375)'), ('Moderately Active', 'Moderate exercise 3-5 days/week (BMR × 1.55)'), ('Very Active', 'Hard exercise 6-7 days/week (BMR × 1.725)'), ('Super Active', 'Very hard exercise/physical job (BMR × 1.9)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='macro_requirements',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='micro_requirements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='api.user'),
        ),
    ]
