# Generated by Django 5.1.6 on 2025-02-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_nutritionplan_carbs_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='height',
            field=models.CharField(default='All', max_length=255),
        ),
    ]
