# Generated by Django 5.1.6 on 2025-02-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_nutritionplan_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='weight',
            field=models.CharField(default='Metabolism Factor', max_length=255),
        ),
    ]
