# Generated by Django 5.1.6 on 2025-02-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_nutritionplan_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='factor_value',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
