# Generated by Django 5.1.6 on 2025-02-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_nutritionplan_factor_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='macro_requirements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='micro_requirements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='arsenic_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='boron_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='calcium_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='carbohydrates_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chloride_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chromium_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='copper_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_calories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fats_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fluoride_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='iodine_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='iron_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='magnesium_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manganese_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='molybdenum_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickel_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nutrition_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nutritionplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='phosphorus_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proteins_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='selenium_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='silicon_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sodium_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vanadium_ug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='zinc_mg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='UserMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietaryplan', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('mealofDay', models.JSONField(default=list)),
                ('daily_calories', models.CharField(default='na', max_length=255)),
                ('carbohydrates_g', models.CharField(default='na', max_length=255)),
                ('proteins_g', models.CharField(default='na', max_length=255)),
                ('fats_g', models.CharField(default='na', max_length=255)),
                ('hydration', models.CharField(default='na', max_length=255)),
                ('boron_mg', models.CharField(default='na', max_length=255)),
                ('calcium_mg', models.CharField(default='na', max_length=255)),
                ('copper_ug', models.CharField(default='na', max_length=255)),
                ('fluoride_mg', models.CharField(default='na', max_length=255)),
                ('iodine_ug', models.CharField(default='na', max_length=255)),
                ('iron_mg', models.CharField(default='na', max_length=255)),
                ('magnesium_mg', models.CharField(default='na', max_length=255)),
                ('manganese_mg', models.CharField(default='na', max_length=255)),
                ('molybdenum_ug', models.CharField(default='na', max_length=255)),
                ('nickel_ug', models.CharField(default='na', max_length=255)),
                ('phosphorus_mg', models.CharField(default='na', max_length=255)),
                ('selenium_ug', models.CharField(default='na', max_length=255)),
                ('vanadium_ug', models.CharField(default='na', max_length=255)),
                ('zinc_mg', models.CharField(default='na', max_length=255)),
                ('sodium_mg', models.CharField(default='na', max_length=255)),
                ('chloride_g', models.CharField(default='na', max_length=255)),
                ('arsenic_ug', models.CharField(default='na', max_length=255)),
                ('chromium_ug', models.CharField(default='na', max_length=255)),
                ('silicon_mg', models.CharField(default='na', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
