# Generated by Django 5.1.6 on 2025-02-16 19:20

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='arsenic_ug',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='chloride_g',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='chromium_ug',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='copper_ug',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='fluoride_mg',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='iodine_ug',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='magnesium_mg',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='manganese_mg',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='molybdenum_ug',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='nickel_ug',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='phosphorus_mg',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='silicon_mg',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='source',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='vanadium_ug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='arsenic_ug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chloride_g',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chromium_ug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='copper_ug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fluoride_mg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iodine_ug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='magnesium_mg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manganese_mg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='molybdenum_ug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickel_ug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phosphorus_mg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='silicon_mg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vanadium_ug',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='arsenic_ug',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='chloride_g',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='chromium_ug',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='copper_ug',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='dietaryplan',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='fluoride_mg',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='iodine_ug',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='magnesium_mg',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='manganese_mg',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='molybdenum_ug',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='nickel_ug',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='phosphorus_mg',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='silicon_mg',
        ),
        migrations.RemoveField(
            model_name='usermeals',
            name='vanadium_ug',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temporarypassword', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='usermeals',
            name='nutrition_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nutritionplan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Little or no exercise (BMR × 1.2)'), ('Lightly Active', 'Light exercise 1-3 days/week (BMR × 1.375)'), ('Moderately Active', 'Moderate exercise 3-5 days/week (BMR × 1.55)'), ('Very Active', 'Hard exercise 6-7 days/week (BMR × 1.725)'), ('Super Active', 'Very hard exercise/physical job (BMR × 1.9)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
